[Variables]

SkinWidth=250

SkinBackgroundColour=40,40,40

BarColour=255,255,255

BarWidth=3

BarHeight=20

BarPadding=12

BarRound=1

BarPosition=1
;0 = top, 1 = center, 2 = bottom

ShowLegends=1

ShowValue=1

LegendFont=Vulf Mono

LegendSize=14

LegendColour=255,255,255

LegendPosition=1
;0 = top, 1 = bottom

LegendPadding=8

IndicatorColour=255,0,0

BorderColour=0,0,0

BorderRound=1

ValueAverage=5

Gradient=1

GradientColour=0,0,0
